export { default as Loader } from "./Loader";
export { default as NavBar } from "./NavBar";
export { default as MovieDetails } from "./MovieDetails";
export { default as Recommendition } from "./Recommendition";
export { default as TrailerModal } from "./TrailerModal";
export { default as Error } from "./Error";
export { default as Row } from "./Row";
export { default as CardsContainer } from "./CardsContainer";
export { default as CategoryTitle } from "./CategoryTitle";
